one = input('enter something plural: ') 
two = input('enter the color of the last object you chose: ')
three = input('enter another plural noun that is blue: ') 
five = input('enter something you like: ')
six = input('enter a verb: ')

print(one, 'are', two)
print(three, 'are blue') 
print('I like', five)
print('but I love', six, 'children too')
